version: "3.3"
services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: sqlTool
    volumes:
      - ./test.sql:/docker-entrypoint-initdb.d/test.sql
    ports:
      - "5436:5432"
