version: "3.3"
services:
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: sqltool
    volumes:
      - ./db_from_course.sql:/docker-entrypoint-initdb.d/db_from_course.sql
    ports:
      - "5436:5432"
