version: "3.3"
services:
  db:
    image: nouchka/sqlite3:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: sqltool
    volumes:
      - ./db_from_course.sqlite3:/docker-entrypoint-initdb.d/db_from_course.sqlite3
    ports:
      - "5437:5432"